<?php


namespace mdm\admin\components;

use yii\web\Controller;

class MdmController extends Controller
{
//    public $layout = 'top-menu';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}