<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "blood_type".
 *
 * @property string $blood_id
 * @property string $name
 * @property int $s_order
 * @property string|null $created_by
 * @property string|null $created_time
 *
 * @property Patient[] $patients
 */
class BloodType extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'blood_type';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['blood_id', 'name', 's_order'], 'required'],
            [['s_order'], 'default', 'value' => null],
            [['s_order'], 'integer'],
            [['created_time'], 'safe'],
            [['blood_id'], 'string', 'max' => 3],
            [['name'], 'string', 'max' => 100],
            [['created_by'], 'string', 'max' => 20],
            [['blood_id'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'blood_id' => Yii::t('app', 'Blood ID'),
            'name' => Yii::t('app', 'Blood Name'),
            's_order' => Yii::t('app', 'Order'),
            'created_by' => Yii::t('app', 'Created By'),
            'created_time' => Yii::t('app', 'Created Time'),
        ];
    }

    /**
     * Gets query for [[Patients]].
     *
     * @return \yii\db\ActiveQuery|PatientQuery
     */
    public function getPatients()
    {
        return $this->hasMany(Patient::className(), ['blood_id' => 'blood_id']);
    }

    /**
     * {@inheritdoc}
     * @return BloodTypeQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new BloodTypeQuery(get_called_class());
    }

    public function afterFind()
    {
        $this->created_time = date('d-m-Y H:i:s', strtotime($this->created_time));
        parent::afterFind(); // TODO: Change the autogenerated stub
    }

    public function beforeSave($insert)
    {
        $this->created_by = Yii::$app->user->getId();
        $this->created_time = date('Y-m-d H:i:s');
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
