<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "employee".
 *
 * @property int $person_id
 * @property string $employee_id
 * @property string $person_name
 * @property string $email
 * @property string $phone
 * @property string $date_of_bird
 * @property string $address
 * @property int $hospital_id
 * @property string|null $created_by
 * @property string|null $created_time
 */
class Employee extends \yii\db\ActiveRecord
{
    public $username;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'employee';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['employee_id', 'person_name', 'email', 'phone', 'date_of_bird', 'address', 'hospital_id'], 'required'],
            [['date_of_bird', 'created_time'], 'safe'],
            [['address'], 'string'],
            [['hospital_id'], 'default', 'value' => null],
            [['hospital_id'], 'integer'],
            [['email'], 'email'],
            [['date_of_bird'], 'datetime', 'format' => 'php:d-m-Y'],
            [['employee_id', 'email'], 'string', 'max' => 50],
            [['person_name'], 'string', 'max' => 255],
            [['phone', 'created_by'], 'string', 'max' => 20],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'person_id' => Yii::t('app', 'Person ID'),
            'employee_id' => Yii::t('app', 'Employee ID'),
            'person_name' => Yii::t('app', 'Person Name'),
            'email' => Yii::t('app', 'Email'),
            'phone' => Yii::t('app', 'Phone'),
            'date_of_bird' => Yii::t('app', 'Date Of Bird'),
            'address' => Yii::t('app', 'Address'),
            'hospital_id' => Yii::t('app', 'Hospital ID'),
            'created_by' => Yii::t('app', 'Created By'),
            'created_time' => Yii::t('app', 'Created Time'),
        ];
    }

    /**
     * Gets query for [[District]].
     *
     * @return \yii\db\ActiveQuery|DistrictQuery
     */
    public function getHospital()
    {
        return $this->hasOne(Hospital::className(), ['hospital_id' => 'hospital_id']);
    }

    public function getUsers()
    {
        return $this->hasOne(User::className(), ['person_id' => 'person_id']);
    }


    /**
     * {@inheritdoc}
     * @return EmployeeQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new EmployeeQuery(get_called_class());
    }

    public function beforeValidate()
    {
        $this->hospital_id = Yii::$app->user->identity->hospital_id;
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    public function beforeSave($insert)
    {
        $this->person_name = strtoupper($this->person_name);
        $this->date_of_bird = date('Y-m-d', strtotime($this->date_of_bird));
        $this->created_by = Yii::$app->user->identity->username;
        $this->created_time = date('Y-m-d H:i:s');
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
