<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "ethnic".
 *
 * @property string $ethnic_id
 * @property string $ethnic_name
 * @property string|null $created_by
 * @property string|null $created_time
 *
 * @property Patient[] $patients
 */
class Ethnic extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'ethnic';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['ethnic_id', 'ethnic_name', 's_order'], 'required'],
            [['created_time'], 'safe'],
            [['ethnic_id'], 'string', 'max' => 2],
            [['ethnic_name'], 'string', 'max' => 50],
            [['created_by'], 'string', 'max' => 20],
            [['ethnic_id'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'ethnic_id' => Yii::t('app', 'Ethnic ID'),
            'ethnic_name' => Yii::t('app', 'Ethnic Name'),
            'created_by' => Yii::t('app', 'Created By'),
            'created_time' => Yii::t('app', 'Created Time'),
        ];
    }

    /**
     * Gets query for [[Patients]].
     *
     * @return \yii\db\ActiveQuery|PatientQuery
     */
    public function getPatients()
    {
        return $this->hasMany(Patient::className(), ['ethnic_id' => 'ethnic_id']);
    }

    /**
     * {@inheritdoc}
     * @return EthnicQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new EthnicQuery(get_called_class());
    }

    public function afterFind()
    {
        $this->created_time = date('d-m-Y H:i:s', strtotime($this->created_time));
        parent::afterFind(); // TODO: Change the autogenerated stub
    }

    public function beforeSave($insert)
    {
        $this->created_by = Yii::$app->user->getId();
        $this->created_time = date('Y-m-d H:i:s');
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
