<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "gender".
 *
 * @property string $gender_id
 * @property string $name
 * @property string $created_by
 * @property string $created_time
 *
 * @property Patient[] $patients
 */
class Gender extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'gender';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['gender_id', 'name'], 'required'],
            [['created_time'], 'safe'],
            [['gender_id'], 'string', 'max' => 2],
            [['name'], 'string', 'max' => 100],
            [['created_by'], 'string', 'max' => 20],
            [['gender_id'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'gender_id' => Yii::t('app', 'Gender ID'),
            'name' => Yii::t('app', 'Gender Name'),
            'created_by' => Yii::t('app', 'Created By'),
            'created_time' => Yii::t('app', 'Created Time'),
        ];
    }

    /**
     * Gets query for [[Patients]].
     *
     * @return \yii\db\ActiveQuery|PatientQuery
     */
    public function getPatients()
    {
        return $this->hasMany(Patient::className(), ['gender_id' => 'gender_id']);
    }

    /**
     * {@inheritdoc}
     * @return GenderQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new GenderQuery(get_called_class());
    }

    public function afterFind()
    {
        $this->created_time = date('d-m-Y H:i:s', strtotime($this->created_time));
        parent::afterFind(); // TODO: Change the autogenerated stub
    }

    public function beforeSave($insert)
    {
        $this->created_by = Yii::$app->user->getId();
        $this->created_time = date('Y-m-d H:i:s');
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

}
