<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "job".
 *
 * @property int $job_id
 * @property int $hospital_id
 * @property string $name
 * @property int $s_order
 * @property int $created_by
 * @property string $created_time
 *
 * @property Hospital $hospital
 * @property User $createdBy
 * @property Patient[] $patients
 */
class Job extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'job';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name', 's_order'], 'required'],
            [['hospital_id', 's_order', 'created_by'], 'default', 'value' => null],
            [['hospital_id', 's_order', 'created_by'], 'integer'],
            [['created_time'], 'safe'],
            [['name'], 'string', 'max' => 100],
            [['hospital_id'], 'exist', 'skipOnError' => true, 'targetClass' => Hospital::className(), 'targetAttribute' => ['hospital_id' => 'hospital_id']],
            [['created_by'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['created_by' => 'user_id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'job_id' => Yii::t('app', 'Job ID'),
            'hospital_id' => Yii::t('app', 'Hospital ID'),
            'name' => Yii::t('app', 'Name'),
            's_order' => Yii::t('app', 'S Order'),
            'created_by' => Yii::t('app', 'Created By'),
            'created_time' => Yii::t('app', 'Created Time'),
        ];
    }

    /**
     * Gets query for [[Hospital]].
     *
     * @return \yii\db\ActiveQuery|HospitalQuery
     */
    public function getHospital()
    {
        return $this->hasOne(Hospital::className(), ['hospital_id' => 'hospital_id']);
    }

    /**
     * Gets query for [[CreatedBy]].
     *
     * @return \yii\db\ActiveQuery|UsersQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(User::className(), ['user_id' => 'created_by']);
    }

    /**
     * Gets query for [[Patients]].
     *
     * @return \yii\db\ActiveQuery|PatientQuery
     */
    public function getPatients()
    {
        return $this->hasMany(Patient::className(), ['job_id' => 'job_id']);
    }

    /**
     * {@inheritdoc}
     * @return JobQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new JobQuery(get_called_class());
    }

    public function beforeSave($insert)
    {
        $this->hospital_id = Yii::$app->user->identity->hospital_id;
        if ($this->isNewRecord) {
            $this->created_by = Yii::$app->user->getId();
            $this->created_time = date('Y-m-d H:i:s');
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

}
