<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "marital_status".
 *
 * @property string $marital_status_id
 * @property string|null $name
 * @property int|null $created_by
 * @property string|null $created_time
 *
 * @property User $createdBy
 * @property Patient[] $patients
 */
class MaritalStatus extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'marital_status';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['marital_status_id'], 'required'],
            [['created_by'], 'default', 'value' => null],
            [['created_by'], 'integer'],
            [['created_time'], 'safe'],
            [['marital_status_id'], 'string', 'max' => 2],
            [['name'], 'string', 'max' => 100],
            [['marital_status_id'], 'unique'],
            [['created_by'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['created_by' => 'user_id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'marital_status_id' => Yii::t('app', 'Marital Status ID'),
            'name' => Yii::t('app', 'Name'),
            'created_by' => Yii::t('app', 'Created By'),
            'created_time' => Yii::t('app', 'Created Time'),
        ];
    }

    /**
     * Gets query for [[CreatedBy]].
     *
     * @return \yii\db\ActiveQuery|UsersQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(User::className(), ['user_id' => 'created_by']);
    }

    /**
     * Gets query for [[Patients]].
     *
     * @return \yii\db\ActiveQuery|PatientQuery
     */
    public function getPatients()
    {
        return $this->hasMany(Patient::className(), ['marital_status_id' => 'marital_status_id']);
    }

    /**
     * {@inheritdoc}
     * @return MaritalStatusQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new MaritalStatusQuery(get_called_class());
    }

    public function beforeSave($insert)
    {
        if ($this->isNewRecord) {
            $this->created_by = Yii::$app->user->getId();
            $this->created_time = date('Y-m-d H:i:s');
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
