<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "patient_rate_group".
 *
 * @property string $prg_id
 * @property string $name
 * @property int|null $created_by
 * @property string|null $created_time
 */
class PatientRateGroup extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'patient_rate_group';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['prg_id', 'name'], 'required'],
            [['created_by'], 'default', 'value' => null],
            [['created_by'], 'integer'],
            [['created_time'], 'safe'],
            [['prg_id'], 'string', 'max' => 2],
            [['name'], 'string', 'max' => 100],
            [['prg_id'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'prg_id' => Yii::t('app', 'Prg ID'),
            'name' => Yii::t('app', 'Name'),
            'created_by' => Yii::t('app', 'Created By'),
            'created_time' => Yii::t('app', 'Created Time'),
        ];
    }

    /**
     * Gets query for [[CreatedBy]].
     *
     * @return \yii\db\ActiveQuery|UsersQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(User::className(), ['user_id' => 'created_by']);
    }

    /**
     * {@inheritdoc}
     * @return PatientRateGroupQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new PatientRateGroupQuery(get_called_class());
    }

    public function beforeSave($insert)
    {
        if ($this->isNewRecord) {
            $this->created_by = Yii::$app->user->getId();
            $this->created_time = date('Y-m-d H:i:s');
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
