<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "registration_status".
 *
 * @property string $regstts_id
 * @property string $reg_status
 * @property int|null $created_by
 * @property string|null $created_time
 *
 * @property Registration[] $registrations
 * @property User $createdBy
 */
class RegistrationStatus extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'registration_status';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['regstts_id', 'reg_status'], 'required'],
            [['created_by'], 'default', 'value' => null],
            [['created_by'], 'integer'],
            [['created_time'], 'safe'],
            [['regstts_id'], 'string', 'max' => 2],
            [['reg_status'], 'string', 'max' => 100],
            [['regstts_id'], 'unique'],
            [['created_by'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['created_by' => 'user_id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'regstts_id' => Yii::t('app', 'Regstts ID'),
            'reg_status' => Yii::t('app', 'Reg Status'),
            'created_by' => Yii::t('app', 'Created By'),
            'created_time' => Yii::t('app', 'Created Time'),
        ];
    }

    /**
     * Gets query for [[Registrations]].
     *
     * @return \yii\db\ActiveQuery|RegistrationQuery
     */
    public function getRegistrations()
    {
        return $this->hasMany(Registration::className(), ['regstts_id' => 'regstts_id']);
    }

    /**
     * Gets query for [[CreatedBy]].
     *
     * @return \yii\db\ActiveQuery|UsersQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(User::className(), ['user_id' => 'created_by']);
    }

    /**
     * {@inheritdoc}
     * @return RegistrationStatusQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new RegistrationStatusQuery(get_called_class());
    }

    public function beforeSave($insert)
    {
        if ($this->isNewRecord) {
            $this->created_by = Yii::$app->user->getId();
            $this->created_time = date('Y-m-d H:i:s');
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
