<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "religion".
 *
 * @property string $religion_id
 * @property string $name
 * @property integer $s_order
 * @property string|null $created_by
 * @property string|null $created_time
 *
 * @property Patient[] $patients
 */
class Religion extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'religion';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['religion_id', 'name', 's_order'], 'required'],
            [['created_time'], 'safe'],
            [['religion_id'], 'string', 'max' => 2],
            [['s_order'], 'integer'],
            [['name'], 'string', 'max' => 100],
            [['created_by'], 'string', 'max' => 20],
            [['religion_id'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'religion_id' => Yii::t('app', 'Religion ID'),
            'name' => Yii::t('app', 'Religion Name'),
            's_order' => Yii::t('app', 'Order'),
            'created_by' => Yii::t('app', 'Created By'),
            'created_time' => Yii::t('app', 'Created Time'),
        ];
    }

    /**
     * Gets query for [[Patients]].
     *
     * @return \yii\db\ActiveQuery|PatientQuery
     */
    public function getPatients()
    {
        return $this->hasMany(Patient::className(), ['religion_id' => 'religion_id']);
    }

    /**
     * {@inheritdoc}
     * @return ReligionQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new ReligionQuery(get_called_class());
    }


    public function afterFind()
    {
        $this->created_time = date('d-m-Y H:i:s', strtotime($this->created_time));
        parent::afterFind(); // TODO: Change the autogenerated stub
    }

    public function beforeSave($insert)
    {
        $this->created_by = Yii::$app->user->getId();
        $this->created_time = date('Y-m-d H:i:s');
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
