<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "room".
 *
 * @property int $room_id
 * @property int $hospital_id
 * @property int|null $clstroom_id
 * @property string|null $room_name
 * @property bool|null $is_active
 * @property int|null $created_by
 * @property string|null $created_time
 * @property int|null $updated_by
 * @property string|null $updated_time
 *
 * @property Bed[] $beds
 * @property ClusterRoom $clstroom
 * @property Hospital $hospital
 * @property User $createdBy
 * @property User $updatedBy
 */
class Room extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'room';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['hospital_id'], 'required'],
            [['hospital_id', 'clstroom_id', 'created_by', 'updated_by'], 'default', 'value' => null],
            [['hospital_id', 'clstroom_id', 'created_by', 'updated_by'], 'integer'],
            [['is_active'], 'boolean'],
            [['created_time', 'updated_time'], 'safe'],
            [['room_name'], 'string', 'max' => 30],
            [['clstroom_id'], 'exist', 'skipOnError' => true, 'targetClass' => ClusterRoom::className(), 'targetAttribute' => ['clstroom_id' => 'clstroom_id']],
            [['hospital_id'], 'exist', 'skipOnError' => true, 'targetClass' => Hospital::className(), 'targetAttribute' => ['hospital_id' => 'hospital_id']],
            [['created_by'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['created_by' => 'user_id']],
            [['updated_by'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['updated_by' => 'user_id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'room_id' => Yii::t('app', 'Room ID'),
            'hospital_id' => Yii::t('app', 'Hospital ID'),
            'clstroom_id' => Yii::t('app', 'Cluster'),
            'room_name' => Yii::t('app', 'Room Name'),
            'is_active' => Yii::t('app', 'Is Active'),
            'created_by' => Yii::t('app', 'Created By'),
            'created_time' => Yii::t('app', 'Created Time'),
            'updated_by' => Yii::t('app', 'Updated By'),
            'updated_time' => Yii::t('app', 'Updated Time'),
        ];
    }

    /**
     * Gets query for [[Beds]].
     *
     * @return \yii\db\ActiveQuery|BedQuery
     */
    public function getBeds()
    {
        return $this->hasMany(Bed::className(), ['room_id' => 'room_id']);
    }

    /**
     * Gets query for [[Clstroom]].
     *
     * @return \yii\db\ActiveQuery|ClusterRoomQuery
     */
    public function getClstroom()
    {
        return $this->hasOne(ClusterRoom::className(), ['clstroom_id' => 'clstroom_id']);
    }

    /**
     * Gets query for [[Hospital]].
     *
     * @return \yii\db\ActiveQuery|HospitalQuery
     */
    public function getHospital()
    {
        return $this->hasOne(Hospital::className(), ['hospital_id' => 'hospital_id']);
    }

    /**
     * Gets query for [[CreatedBy]].
     *
     * @return \yii\db\ActiveQuery|UsersQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(User::className(), ['user_id' => 'created_by']);
    }

    /**
     * Gets query for [[UpdatedBy]].
     *
     * @return \yii\db\ActiveQuery|UsersQuery
     */
    public function getUpdatedBy()
    {
        return $this->hasOne(User::className(), ['user_id' => 'updated_by']);
    }

    /**
     * {@inheritdoc}
     * @return RoomQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new RoomQuery(get_called_class());
    }

    public function beforeSave($insert)
    {
        $this->room_name = strtoupper($this->room_name);
        if ($this->isNewRecord) {
            $this->created_by = Yii::$app->user->getId();
            $this->created_time = date('Y-m-d H:i:s');
        }
        $this->updated_by = Yii::$app->user->getId();
        $this->updated_time = date('Y-m-d H:i:s');

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public static function getActive()
    {
        return self::find()->where(['hospital_id' => Yii::$app->user->identity->hospital_id, 'is_active' => true])->all();
    }
}
