<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "subdistrict".
 *
 * @property string $subdistrict_id
 * @property string $district_id
 * @property string $subdistrict_name
 * @property string|null $created_by
 * @property string|null $created_time
 *
 * @property NonPatient[] $nonPatients
 * @property Patient[] $patients
 * @property District $district
 */
class Subdistrict extends \yii\db\ActiveRecord
{
    public $prv_id, $region;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'subdistrict';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['subdistrict_id', 'district_id', 'subdistrict_name'], 'required'],
            [['created_time'], 'safe'],
            [['subdistrict_id', 'district_id'], 'string', 'max' => 10],
            [['subdistrict_name'], 'string', 'max' => 100],
            [['created_by'], 'string', 'max' => 20],
            [['subdistrict_id'], 'unique'],
            [['district_id'], 'exist', 'skipOnError' => true, 'targetClass' => District::className(), 'targetAttribute' => ['district_id' => 'district_id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'subdistrict_id' => Yii::t('app', 'Subdistrict ID'),
            'district_id' => Yii::t('app', 'District ID'),
            'subdistrict_name' => Yii::t('app', 'Subdistrict Name'),
            'prv_id' => Yii::t('app', 'Prv Name'),
            'created_by' => Yii::t('app', 'Created By'),
            'created_time' => Yii::t('app', 'Created Time'),
        ];
    }

    /**
     * Gets query for [[NonPatients]].
     *
     * @return \yii\db\ActiveQuery|NonPatientQuery
     */
    public function getNonPatients()
    {
        return $this->hasMany(NonPatient::className(), ['subdistrict_id' => 'subdistrict_id']);
    }

    /**
     * Gets query for [[Patients]].
     *
     * @return \yii\db\ActiveQuery|PatientQuery
     */
    public function getPatients()
    {
        return $this->hasMany(Patient::className(), ['subdistrict_id' => 'subdistrict_id']);
    }

    /**
     * Gets query for [[District]].
     *
     * @return \yii\db\ActiveQuery|DistrictQuery
     */
    public function getDistrict()
    {
        return $this->hasOne(District::className(), ['district_id' => 'district_id']);
    }

    /**
     * {@inheritdoc}
     * @return SubdistrictQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new SubdistrictQuery(get_called_class());
    }

    public function getFullSubdistrict()
    {
        return $this->subdistrict_name . '/' . $this->district->district_name . '/' . $this->district->prv->prv_name;
    }

    public function afterFind()
    {
        $this->created_time = date('d-m-Y H:i:s', strtotime($this->created_time));
        parent::afterFind(); // TODO: Change the autogenerated stub
    }

    public function beforeSave($insert)
    {
        $this->created_by = Yii::$app->user->getId();
        $this->created_time = date('Y-m-d H:i:s');
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
